version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  publisher:
    build: ./publisher
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - EXCHANGE_NAME=${EXCHANGE_NAME}
      - QUEUE_NAME=${QUEUE_NAME}
      - ROUTING_KEY=${ROUTING_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build: ./consumer
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
      - EXCHANGE_NAME=${EXCHANGE_NAME}
      - QUEUE_NAME=${QUEUE_NAME}
      - ROUTING_KEY=${ROUTING_KEY}
    depends_on:
      rabbitmq:
        condition: service_healthy
