global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq:15672']
    basic_auth:
      username: '${RABBITMQ_USER}'
      password: '${RABBITMQ_PASS}'
      
  - job_name: 'node-apps'
    static_configs:
      - targets: ['publisher:3000', 'consumer:3000']